tls:
    certificates:
        - certFile: /etc/cert/self-signed.crt
          keyFile: /etc/cert/self-signed.key
    options:
        default:
            minVersion: VersionTLS12
            # sniStrict: true
            cipherSuites:
                # TLS 1.3
                - TLS_AES_256_GCM_SHA384
                - TLS_AES_128_GCM_SHA256
                - TLS_CHACHA20_POLY1305_SHA256
                # TLS 1.2
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            curvePreferences:
                # - X25519MLKEM768
                - X25519
                - CurveP256
                - CurveP384
